name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd frontend/reliabilityiq
          npm install

      - name: Build project
        run: |
          cd frontend/reliabilityiq
          npm run build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "reliabilityiq" 
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          used_node: true
          buildpack: heroku/nodejs
          branch: main
          region: us


